/* Generated by AN DISI Unibo */
package it.unibo.ctx_trolley

import it.unibo.kactor.QakContext
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
    QakContext.createContexts(
        "localhost", this, "wasteservice.pl", "sysRules.pl"
    )
}

