/* Generated by AN DISI Unibo */ 
package it.unibo.ctx_statusgui
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "wasteservice_proto_sprint3_contexts.pl", "sysRules.pl","ctx_statusgui"
	)
}

