version: '3' # optional since v1.27.0
services:
  wenv:
    image: docker.io/lnwor/virtualrobotdisi:4.3
    #image: virtualrobotdisi:4.3
    ports:
      - 8090:8090 
      - 8091:8091/tcp
      - 8091:8091/udp
  robot:
    image: docker.io/natbodocker/basicrobot22:1.0
    #image: basicrobot22:1.0
    ports:
      - 8020:8020/tcp
      - 8020:8020/udp
    depends_on:
      - wenv
  wasteservice.core:
    image: docker.io/filloax/wasteservice.core:0.2
    ports:
      - 8080:8080/tcp
      - 8080:8080/udp
      - 8023:8023/tcp
      - 8023:8023/udp
    depends_on:
      - robot
  wasteservice.led:
    image: docker.io/filloax/wasteservice.led.mock:0.2
    ports:
      - 8030:8030/tcp
      - 8030:8030/udp
    depends_on:
      - wasteservice.core
  wasteservice.statusgui:
    image: docker.io/filloax/wasteservice.statusgui:0.2
    ports:
      - 8095:8095/tcp
      - 8095:8095/udp
    depends_on:
      - wasteservice.core
      - wasteservice.led