version: '3' # optional since v1.27.0
services:
  wenv:
    image: docker.io/lnwor/virtualrobotdisi:4.3
    ports:
      - 8090:8090 
      - 8091:8091/tcp
      - 8091:8091/udp
  # robot:
  #   extra_hosts:
  #     wenv: 79.17.203.217 # 127.0.0.1
  #   image: docker.io/natbodocker/basicrobot22:2.0
  #   #image: basicrobot22:1.0
  #   ports:
  #     - 8020:8020/tcp
  #     - 8020:8020/udp
  unibo.pathexecstop:
    extra_hosts:
      robot: 192.168.166.115
    image: docker.io/lnwor/unibo.pathexecstop:1.1
    ports:
      - 8025:8025/tcp
      - 8025:8025/udp
    # depends_on:
    #   - robot
  wasteservice.core:
    image: docker.io/lnwor/wasteservice.core:1.2
    ports:
      - 8080:8080/tcp
      - 8080:8080/udp
      - 8023:8023/tcp
      - 8023:8023/udp
    depends_on:
      - unibo.pathexecstop
  wasteservice.trolley:
    image: docker.io/lnwor/wasteservice.trolley:1.0
    ports:
      - 8070:8070/tcp
      - 8070:8070/udp
    depends_on:
      - wasteservice.core
  wasteservice.storage:
    image: docker.io/lnwor/wasteservice.storage:1.0
    ports:
      - 8071:8071/tcp
      - 8071:8071/udp
    depends_on:
      - wasteservice.core
  wasteservice.raspgui:
    hostname: wasteservice.led
    image: docker.io/filloax/wasteservice.raspgui:1.1
    ports:
      - 8096:8096/tcp
      - 8096:8096/udp
    depends_on:
      - wasteservice.core
  wasteservice.statusgui:
    image: docker.io/lnwor/wasteservice.statusgui:2.0
    ports:
      - 8095:8095/tcp
      - 8095:8095/udp
    depends_on:
      - wasteservice.core
      - wasteservice.raspgui
