/* Generated by AN DISI Unibo */ 
package it.unibo.gui

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Gui ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var TrolleyPos = ""
				var TrolleyStatus = ""
				var LedStatus =	""
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						coapObserverUtil.startObserving(myself ,"trolley" )
						coapObserverUtil.startObserving(myself ,"led" )
						coapObserverUtil.startObserving(myself ,"wasteservice" )
					}
					 transition( edgeName="goto",targetState="show", cond=doswitch() )
				}	 
				state("show") { //this:State
					action { //it:State
						println("	GUI: Trolley [Position: $TrolleyPos, Status: $TrolleyStatus], Led [$LedStatus]")
					}
					 transition(edgeName="t02",targetState="handleUpdate",cond=whenDispatch("coapUpdate"))
				}	 
				state("handleUpdate") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("coapUpdate(RESOURCE,VALUE)"), Term.createTerm("coapUpdate(RESOURCE,VALUE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  payloadArg(0) == "trolley"  
								 ){ TrolleyStatus = resourcePrologUtils.resourcePayloadArg(myself, "state", 0)  
								}
								if(  payloadArg(0) == "led"  
								 ){ LedStatus = resourcePrologUtils.resourcePayloadArg(myself, "ledState", 0)  
								}
								if(  payloadArg(0) == "wasteservice"  
								 ){ TrolleyPos = resourcePrologUtils.resourcePayloadArg(myself, "tpos", 0)  
								}
						}
					}
					 transition( edgeName="goto",targetState="show", cond=doswitch() )
				}	 
			}
		}
}
