/* Generated by AN DISI Unibo */ 
package it.unibo.pro_dep_storagemanager

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Pro_dep_storagemanager ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "idle"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var Content = mutableMapOf("glass" to 0.0, "plastic" to 0.0)
		return { //this:ActionBasciFsm
				state("idle") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("STORAGE: Glass ${Content["glass"]}, Plastic ${Content["plastic"]}")
						updateResourceRep( Content.entries.map { "content(${it.key},${it.value})" }.joinToString("\n")  
						)
					}
					 transition(edgeName="t011",targetState="handleDeposit",cond=whenDispatch("storageDeposit"))
				}	 
				state("handleDeposit") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("storageDeposit(MAT,QNT)"), Term.createTerm("depositWaste(MAT,QNT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Content[payloadArg(0)] = Content.getOrDefault(payloadArg(0), 0.0) + payloadArg(1).toDouble()  
						}
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
}
