/* Generated by AN DISI Unibo */ 
package it.unibo.ctxpro_sonar_stop
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "wasteservice_pro_sonar_stop.pl", "sysRules.pl"
	)
}

