version: '3' # optional since v1.27.0
services:
  wenv:
    image: docker.io/lnwor/virtualrobotdisi:4.3
    #image: virtualrobotdisi:4.3
    ports:
      - 8090:8090 
      - 8091:8091/tcp
      - 8091:8091/udp
  robot:
    image: docker.io/natbodocker/basicrobot22:2.0
    #image: basicrobot22:1.0
    ports:
      - 8020:8020/tcp
      - 8020:8020/udp
    depends_on:
      - wenv
  unibo.pathexecstop:
    image: docker.io/lnwor/unibo.pathexecstop:1.0
    ports:
      - 8025:8025/tcp
      - 8025:8025/udp

## -------------------------------------------------------------
## TODO See https://docs.docker.com/compose/startup-order/
## -------------------------------------------------------------
## docker-compose -f basicrobot22.yaml  up
## docker-compose run --service-ports wenv
## docker-compose run --service-ports vrobotclient  ATTIVA ANCHE wenv
