/* Generated by AN DISI Unibo */ 
package it.unibo.trolley

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Trolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "goingIndoor"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("goingIndoor") { //this:State
					action { //it:State
						println("Going INDOOR")
						delay(1000) 
						println("At INDOOR")
						request("ping", "ping(_)" ,"echo" )  
					}
					 transition(edgeName="t02",targetState="goingBox",cond=whenReply("pong"))
					interrupthandle(edgeName="t03",targetState="handleStop",cond=whenDispatch("trolleyStop"),interruptedStateTransitions)
				}	 
				state("goingBox") { //this:State
					action { //it:State
						println("Going BOX")
						delay(1000) 
						println("At BOX")
						request("ping", "ping(_)" ,"echo" )  
					}
					 transition(edgeName="t14",targetState="goingHome",cond=whenReply("pong"))
					interrupthandle(edgeName="t15",targetState="handleStop",cond=whenDispatch("trolleyStop"),interruptedStateTransitions)
				}	 
				state("goingHome") { //this:State
					action { //it:State
						println("Going HOME")
						delay(1000) 
						println("At HOME")
						request("ping", "ping(_)" ,"echo" )  
					}
					 transition(edgeName="t26",targetState="goingIndoor",cond=whenReply("pong"))
					interrupthandle(edgeName="t27",targetState="handleStop",cond=whenDispatch("trolleyStop"),interruptedStateTransitions)
				}	 
				state("exitFromStop") { //this:State
					action { //it:State
						 MsgUtil.outgreen("Trolley resumed!")  
						updateResourceRep( "resumed"  
						)
						returnFromInterrupt(interruptedStateTransitions)
					}
				}	 
				state("handleStop") { //this:State
					action { //it:State
						 MsgUtil.outred("Trolley stopped!")  
						updateResourceRep( "stopped"  
						)
					}
					 transition(edgeName="t38",targetState="exitFromStop",cond=whenDispatch("trolleyResume"))
				}	 
			}
		}
}
