/* Generated by AN DISI Unibo */ 
package it.unibo.ctxpro_deposit
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "wasteservice_pro_deposit.pl", "sysRules.pl"
	)
}

