/* Generated by AN DISI Unibo */ 
package it.unibo.pro_req_wastetruck

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Pro_req_wastetruck ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "req"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var Times = 5	
		return { //this:ActionBasciFsm
				state("req") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						
									var Material = if (kotlin.random.Random.nextFloat() > 0.5) "glass" else "plastic"
									var Quantity = kotlin.random.Random.nextInt(10, 30)	
						println("	Truck with $Material in amount $Quantity arrived")
						request("truckDeposit", "truckDeposit($Material,$Quantity)" ,"pro_req_wasteservice" )  
					}
					 transition(edgeName="t13",targetState="handleAccepted",cond=whenReply("loadaccept"))
					transition(edgeName="t14",targetState="handleRejected",cond=whenReply("loadrejected"))
				}	 
				state("handleRejected") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("	Truck denied")
					}
					 transition( edgeName="goto",targetState="waitArrival", cond=doswitch() )
				}	 
				state("handleAccepted") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("	Truck accepted")
					}
					 transition(edgeName="t05",targetState="waitArrival",cond=whenDispatch("pickedUp"))
				}	 
				state("waitArrival") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						 var DelayTime : kotlin.Long = kotlin.random.Random.nextLong(7000, 10000)  
						delay(DelayTime)
						 Times--  
					}
					 transition( edgeName="goto",targetState="req", cond=doswitchGuarded({ Times > 0  
					}) )
					transition( edgeName="goto",targetState="finish", cond=doswitchGuarded({! ( Times > 0  
					) }) )
				}	 
				state("finish") { //this:State
					action { //it:State
						println("	Termine simulazione Qak")
					}
				}	 
			}
		}
}
