/* Generated by AN DISI Unibo */ 
package it.unibo.gui_wasteservicestatusgui

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Gui_wasteservicestatusgui ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				var TrolleyPos = ""
				var TrolleyStatus = ""
				var LedStatus =	""
				var StoragePlastic = -1f
				var StorageGlass = -1f
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						coapObserverUtil.startObserving(myself ,"trolley_gui" )
						coapObserverUtil.startObserving(myself ,"blinkled_gui" )
						coapObserverUtil.startObserving(myself ,"storage_gui" )
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="show", cond=doswitch() )
				}	 
				state("show") { //this:State
					action { //it:State
						println("	GUI: Trolley [Position: $TrolleyPos, Status: $TrolleyStatus], Led [$LedStatus], Storage: [Glass: $StorageGlass, Plastic: $StoragePlastic]")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleUpdate",cond=whenDispatch("coapUpdate"))
				}	 
				state("handleUpdate") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("coapUpdate(RESOURCE,VALUE)"), Term.createTerm("coapUpdate(RESOURCE,VALUE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  payloadArg(0) == "trolley_gui"  
								 ){
								  					val split = payloadArg(1).split(",")
								  					TrolleyStatus = split[0].trim()
								  					TrolleyPos = split[1].trim()
								}
								if(  payloadArg(0) == "blinkled_gui"  
								 ){ LedStatus = payloadArg(1)  
								}
								if(  payloadArg(0) == "storage_gui"  
								 ){
								  					val split = payloadArg(1).split(",")
								  					StoragePlastic = split[0].trim().toFloat()
								  					StorageGlass = split[1].trim().toFloat()
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="show", cond=doswitch() )
				}	 
			}
		}
}
